### ISSUE TITLE
Please create an Annotated Tag

### ISSUE THREAD

**Issue by envzhu** [LiXi-storage/barreleye#1]
Executing `sh ./autogen.sh` outputs an error like below:
 ```
ERROR: failed to run command [cd /root/develop/barreleye && git describe] on host [machine name], ret = [128], stdout = [], stderr = [fatal: No names found, cannot describe anything.
```
This error is caused by a lack of `Annotated Tag` in the git repository.
So please add an appropriate `Annotated Tag` to this repository.

**Comment by LiXi-storage** [comment]
pushed tag "2.0.0-dev". Please "git pull" and run again.

**Comment by envzhu** [comment]
Thank you!
