### ISSUE TITLE
Failed to install rpm from internet on CentOS8 4.18.0-348.7.1.el8_5.x86_64

### ISSUE THREAD

**Issue by javier2150** [LiXi-storage/barreleye#12]
The commond [yum install  -y createrepo e2fsprogs-devel genisoimage git libtool-ltdl-devel libyaml-devel json-c-devel redhat-lsb-core wget python3-pylint python3-psutil modulemd-tools libcurl-devel ganglia-devel gtk2-devel iptables-devel iproute-devel libatasmart-devel libdbi-devel libcap-devel libesmtp-devel libgcrypt-devel libmemcached-devel libmicrohttpd-devel libmnl-devel libnotify-devel libpcap-devel libssh2-devel libxml2-devel libvirt-devel lm_sensors-devel lua-devel mosquitto-devel net-snmp-devel OpenIPMI-devel openldap-devel perl-ExtUtils-Embed postgresql-devel python-devel qpid-proton-c-devel riemann-c-client-devel rrdtool-devel systemd-devel uthash-devel xfsprogs-devel yajl-devel zeromq-devel] is executed, the setup shell will crash. I find in this OS version, the package "python-devel" cause terrible probles。

I think you can replace "python-devel" with "python36-devel", and "postgresql-devel" with "libpq-devel". 

Meanwhile, the paramenter "--enablerepo=powertools" could be supplemented for "yum" command, therewise, some packages can't be installed.

In addition, in file "pybuild/coral_build.py:333",  the "createrepo" will cause some error to crash program, because the result of  "rpm -q createrepo" mean createrepo not be installed. So, I sovle it via changing "createrepo" to ""createrepo_c".

Please check it and recover soon.

**Comment by LiXi-storage** [comment]
Thanks for the advice. A patch is coming and it is a little bit more complex since both RHEL7 and RHEL8 need to be supported.

**Comment by LiXi-storage** [comment]
Fixed in https://github.com/LiXi-storage/barreleye/commit/2662b0e86c2ed44f3864689a43f77bfb18f067bf
