### ISSUE TITLE
The OSS read/write throughput got wrong number

### ISSUE THREAD

**Issue by QiulanHuang** [LiXi-storage/barreleye#15]
We found the the number OSS read/write throughput is 2 times the actual traffic. Our network is a bond configuration. I guess the data was collected from both the bond0 and the other network interfaces belonging to the bond0 as well.

Can someone help to take a look? What something I missed to config? Thanks.

**Comment by LiXi-storage** [comment]
According to the offline discussion, this issue was due to mis-configuration and has been fixed.
