### ISSUE TITLE
pyinstaller风险

### ISSUE THREAD

**Issue by freyshen** [LiXi-storage/barreleye#5]
谷歌下载pyinstaller会被拦截说有风险，需升级版本到   
https://github.com/pyinstaller/pyinstaller/releases/download/v4.3/pyinstaller-4.3.tar.gz

**Comment by LiXi-storage** [comment]
pyinstall has been updateed to 4.3 with patch b5a84fbf39643821b8bf01a87bf4fbac474dfffe
